### ISSUE TITLE
Legacy tokens for Slack

### ISSUE THREAD

**Issue by chicgeek** [phil-r/slack-emoji#16]
The emoji export config requires an oauth token, which is a method deprecated by Slack. When you visit the url in the example file (https://api.slack.com/docs/oauth-test-tokens) you are redirected to [this page](https://api.slack.com/legacy/custom-integrations/legacy-tokens) with the following message:

> You're reading this because you're looking for info on legacy custom integrations - an outdated way for teams to integrate with Slack. These integrations lack newer features and they will be deprecated and possibly removed in the future. We do not recommend their use.
Instead, we suggest that you read about their replacement - Slack apps. Slack apps can be built just for your own workspace or distributed through the App Directory, and they can use the latest and greatest APIs and UI features.

**Comment by phil-r** [comment]
Thanks, switched to the new thing

**Comment by chicgeek** [comment]
Super quick - I'll give it a whirl shortly.

🎖
