### ISSUE TITLE
npm i?

### ISSUE THREAD

**Issue by nickf352** [phil-r/slack-emoji#6]
I'm stuck on Step 1. 

I entered "npm i" into a Terminal window and nothing happened. Ideas?

**Comment by phil-r** [comment]
Hello @nickf352 👋 

`npm i` is a shortcut for `npm install` to run it you'll need to have [node](https://nodejs.org/) installed.

I guess instructions are a bit unclear, before running `npm i` you need to clone project and move into the project folder. 

If this doesn't help send me your `node` and `npm` versions, you can do this by doing so:

```sh
node -v
npm -v
```

and also send the output of `npm i` command

**Comment by nickf352** [comment]
Oh! I feel like I might've wasted your time - I'll try all this for sure, but it sounds like I just missed something simple/obvious. Thanks for replying. If there's a system where Issues get closed, or if you have a way of removing this as an Issue, feel free. Thanks again

EDIT: I can close Issues! Who knew. Closing! :)

**Comment by phil-r** [comment]
@nickf352 😄 haha all good!
I'm glad to help
